### ISSUE TITLE
组件打包出来的lib目录下没有index.d.ts

### ISSUE THREAD

**Issue by zp1112** [art-design-ui/art-ui#3]
为什么我执行npm run build:types，后得到的lib文件下没有index.d.ts声明文件啊？

![image](https://user-images.githubusercontent.com/14245159/93102915-8e5f3c00-f6de-11ea-982c-ba5ee33d1477.png)

**Comment by BovineBoy** [comment]
> 为什么我执行npm run build:types，后得到的lib文件下没有index.d.ts声明文件啊？
> 
> ![image](https://user-images.githubusercontent.com/14245159/93102915-8e5f3c00-f6de-11ea-982c-ba5ee33d1477.png)

可以将package.json里面的 build:types脚本修改为`"build:types": "tsc -p tsconfig.build.json --listEmittedFiles"`生成生成文件的详细log信息

**Comment by BovineBoy** [comment]
最新的版本添加了 `build:types.log` 命令可以详细查看生成的types文件，你可以运行 `npm run build:types.log` 查看有没有你需要的声明文件

**Comment by zp1112** [comment]
能请问一下，为什么我执行npm run build:types.log报这个错吗？npm run build没报错

![image](https://user-images.githubusercontent.com/14245159/93181936-ac26b280-f76b-11ea-91c9-c0711ea025d2.png)

**Comment by BovineBoy** [comment]
可以删除`node_modules`、`package-lock.json`或`yarn.lock`后重新安装依赖

**Comment by BovineBoy** [comment]
> 能请问一下，为什么我执行npm run build:types.log报这个错吗？npm run build没报错
> 
> ![image](https://user-images.githubusercontent.com/14245159/93181936-ac26b280-f76b-11ea-91c9-c0711ea025d2.png)
你的错误与@types/node这个包有关，这是相关issue，等一下我会发布一个版本用于回退@types/node这个包的版本修复错误
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45993

**Comment by zp1112** [comment]
打包出来的lib下面的d.ts为啥在components文件夹里面呀？
![image](https://user-images.githubusercontent.com/14245159/93191695-68d24100-f777-11ea-9978-93c861f23b24.png)

**Comment by zp1112** [comment]
我觉得这个d.ts是不是好像不太对啊？好像不是声明文件啊

**Comment by zp1112** [comment]
我用这个tsconfig打包出来的可以

```js
{
  "compilerOptions": {
    "baseUrl": ".",
    "lib": ["dom", "dom.iterable", "esnext"],
    "paths": {
      "art": ["src/components/index.ts"],
      "@util": ["src/components/_util"]
    },
    "allowJs": false,
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "outDir": "lib",
    "strict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/components"],
  "exclude": ["node_modules", "**/__tests__/**", "**/demo/**", "lib", "es"]
}
```
但是tsconfig配置的paths别名@util，在打包好组件库，在示例中使用组件库的时候报错`can not resolve @util`，用你的build方法也是一样的好像都没有编译这个@util
![image](https://user-images.githubusercontent.com/14245159/93239774-d735f400-f7b5-11ea-8bcf-afa674eaa94f.png)
